/**
 * Proyect: Sistema de acuerdos y actas municipales (SAA)
 * Company: Municipalidad de Tibás
 * Universidad Nacional de Costa Rica
 * School of Informatic
 * Information Systems Engineering
 * 
 * Date: 10/05/2024
 * Principal_Directory: src
 * Directory: app
 * Archive: layout.jsx
 * 
 * Authors:
 * - Scrum: Luis Ignacio López Castro
 *   - email: luis.lopez.castro@est.una.ac.cr
 *   - ID: 402420889
 * - David Coto Solano
 *   - email: victor.coto.solano@est.una.ac.cr
 *   - ID: 305440064
 * - Andrés León Orozco
 *   - email: andres.leon.orozco@est.una.ac.cr
 *   - ID: 118920778
 * - Eduardo Aarón Ojeda Paladino
 *   - email: eduardo.ojeda.paladino@est.una.ac.cr
 *   - ID: 116500136
 * - Jennifer Quirós Chacón
 *   - email: jennifer.quiros.chacon@est.una.ac.cr
 *   - ID: 702790153
 * - José Miguel Sequeira Hernández
 *   - email: jose.sequeira.hernandez@est.una.ac.cr
 *   - ID: 116590034
 */

import "./globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "./components/header/Navbar";
import { Providers } from "./providers";
import SessionAuthProvider from "./context/SessionAuthProvider";
import AutoLogoutProvider from "./components/utils/SesionInactivityHandler";
import Flowbar from "./components/footer/Flowbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sistema de Acuerdos y Actas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex flex-col min-h-screen dark:bg-gray-800">
        <SessionAuthProvider>
          <AutoLogoutProvider>
            <Providers>
              <Navbar />
              {children}
              <Flowbar />
            </Providers>
          </AutoLogoutProvider>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
