import { Inter } from "next/font/google";
import { Navbar } from "../components/header/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sistema de Actas y Acuerdos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-gray-800">
        <Navbar isAdmin={true} />
        {children}
      </body>
    </html>
  );
}
